# Generated by Django 2.1.3 on 2019-01-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manholeduration',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manholeduration',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
