# Generated by Django 2.1.2 on 2018-10-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'permanent'), ('temporary', 'temporary')], max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('employee', 'Employee')], max_length=150),
        ),
    ]
