# Generated by Django 2.1.2 on 2018-10-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='location',
        ),
        migrations.AddField(
            model_name='sites',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='current_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sites',
            name='expected_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='location_lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='location_long',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_workspace', to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='tools',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_workspace', to='api.Workspace'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='archivedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
