# Generated by Django 2.1.2 on 2018-10-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181029_1712'),
        ('api', '0002_auto_20181027_1905'),
    ]

    operations = [
    ]
