# Generated by Django 2.1.2 on 2018-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sites_workstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='location',
        ),
        migrations.AddField(
            model_name='sites',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='current_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sites',
            name='expected_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='location_lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='location_long',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='archivedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
