# Generated by Django 2.1.2 on 2018-10-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181018_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='workStatus',
            new_name='workspace_id',
        ),
        migrations.AddField(
            model_name='tools',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='workspace_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
    ]
