# Generated by Django 2.1.3 on 2019-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_site_email_remainder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_contact_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
