# Generated by Django 2.1.2 on 2018-11-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181031_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteboq',
            name='quantity',
        ),
    ]
