# Generated by Django 2.1.2 on 2018-10-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181018_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='sites',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_workspace', to='api.Workspace'),
        ),
    ]
