# Generated by Django 2.1.3 on 2019-01-10 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190109_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArrivalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('arrival_time', models.DateTimeField()),
                ('site_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Siterole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteCompletedWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('completed', models.BooleanField(default=False)),
                ('site_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Siterole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('work_status', models.CharField(choices=[('started', 'started'), ('stopped', 'stopped'), ('resumed', 'resumed')], max_length=150)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('site_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Siterole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
