# Generated by Django 2.1.2 on 2018-10-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181031_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_vehicle_type', to='api.FleetType'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_types', to='api.MachineryType'),
        ),
    ]
