# Generated by Django 2.1.2 on 2018-11-06 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181031_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notification', models.CharField(max_length=500, null=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='api.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_name', models.CharField(max_length=50, null=True)),
                ('coordinates_lat', models.CharField(max_length=20, null=True)),
                ('coordinates_long', models.CharField(max_length=20, null=True)),
                ('ack', models.BooleanField(default=False)),
                ('ack_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_ack_user', to='api.User')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_creator', to='api.User')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_surveyor', to='api.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fleettype',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleettype_workspace', to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='machinerytype',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinerytype_workspace', to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='site',
            name='survey_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tooltype',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tooltype_workspace', to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='site',
            name='survey_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_survey_request', to='api.Survey'),
        ),
    ]
