# Generated by Django 2.1.3 on 2019-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sitearrivaltime_sitecompletedworks_siteworkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
