# Generated by Django 2.1.3 on 2019-01-10 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190110_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('not-ok', 'Not ok')], max_length=150, null=True)),
                ('fleet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Fleet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FleetCheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fleetchecklist',
            name='fleet_check_list_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FleetCheckListItem'),
        ),
        migrations.AddField(
            model_name='fleetchecklist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
