# Generated by Django 2.1.3 on 2018-11-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useremailactivation'),
        ('api', '0006_auto_20181106_1418'),
    ]

    operations = [
    ]
