# Generated by Django 2.1.3 on 2019-01-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190110_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetchecklist',
            name='name',
        ),
    ]
