# Generated by Django 2.1.3 on 2018-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20181106_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('isp', 'ISP'), ('osp', 'OSP'), ('quality', 'Quality'), ('ofc', 'OFC'), ('driver', 'Driver'), ('surveyor', 'Surveyor'), ('project_manager', 'Project Manager'), ('fleet_manager', 'Fleet Manager')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('employee', 'Employee'), ('client', 'Client')], max_length=150),
        ),
    ]
