# Generated by Django 2.1.3 on 2018-11-07 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_adding_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_returned', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehousematerial_material', to='api.Material')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehousematerial_site', to='api.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
