# Generated by Django 2.1.3 on 2019-01-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fleethistory_machinehistory_toolhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manholeduration',
            name='duration',
        ),
    ]
