# Generated by Django 2.1.3 on 2018-11-08 06:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181107_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('isp', models.CharField(max_length=50, null=True)),
                ('osp', models.CharField(max_length=50, null=True)),
                ('quality', models.CharField(max_length=50, null=True)),
                ('ofc', models.CharField(max_length=50, null=True)),
                ('driver', models.CharField(max_length=50, null=True)),
                ('surveyor', models.CharField(max_length=50, null=True)),
                ('project_manager', models.CharField(max_length=50, null=True)),
                ('fleet_manager', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
