# Generated by Django 2.1.3 on 2019-01-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
    ]
