# Generated by Django 2.1.3 on 2018-11-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_surveyresultcomment_surveyor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
