# Generated by Django 2.1.3 on 2019-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('fixed', 'Fixed')], max_length=255, null=True),
        ),
    ]
