# Generated by Django 2.1.3 on 2019-01-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='site_connection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_connection_request_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='site_ready_for_connection',
            field=models.BooleanField(default=False),
        ),
    ]
