# Generated by Django 2.1.3 on 2019-01-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190124_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethistory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Site'),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Site'),
        ),
        migrations.AddField(
            model_name='toolhistory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Site'),
        ),
    ]
