# Generated by Django 2.1.3 on 2019-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190128_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
