# Generated by Django 2.1.5 on 2019-02-04 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_comment_fixed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetFuelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requested_fuel_in_litres', models.IntegerField(blank=True, null=True)),
                ('received_fuel_in_litres', models.IntegerField(blank=True, null=True)),
                ('total_fuel_amount', models.IntegerField(blank=True, null=True)),
                ('mileage_at_fuelling_time', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('refuel_reject_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fleet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
