# Generated by Django 2.1.3 on 2018-11-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181113_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='survey_request',
        ),
        migrations.AddField(
            model_name='site',
            name='site_accessible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_surveyed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
