# Generated by Django 2.1.5 on 2019-02-04 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fleetfuelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fuel_in_litres', models.IntegerField(blank=True, null=True)),
                ('total_fuel', models.IntegerField(blank=True, null=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fleet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('isp', 'ISP'), ('osp', 'OSP'), ('quality', 'Quality'), ('ofc', 'OFC'), ('driver', 'Driver'), ('surveyor', 'Surveyor'), ('project_manager', 'Project Manager'), ('fleet_manager', 'Fleet Manager'), ('mechanic', 'Mechanic'), ('mechanic', 'Mechanic'), ('fuel_station_user', 'Fuel Station User')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fuelreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
