# Generated by Django 2.1.5 on 2019-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190204_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='number_of_members_on_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='number_of_site_fleet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_image',
            field=models.FileField(blank=True, null=True, upload_to='sites/'),
        ),
    ]
