# Generated by Django 2.1.5 on 2019-03-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetchecklist',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('isp', 'ISP'), ('osp', 'OSP'), ('osp_field_manager', 'OSP Field Manager'), ('osp_supervisor', 'OSP Supervisor'), ('quality', 'Quality'), ('ofc', 'OFC'), ('driver', 'Driver'), ('surveyor', 'Surveyor'), ('project_manager', 'Project Manager'), ('fleet_manager', 'Fleet Manager'), ('mechanic', 'Mechanic'), ('fuel_station_user', 'Fuel Station User'), ('warehouse', 'warehouse'), ('garage_manager', 'Garage Manager')], max_length=150, null=True),
        ),
    ]
