# Generated by Django 2.1.3 on 2018-11-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_user', to='api.User'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_site', to='api.Site'),
        ),
    ]
