# Generated by Django 2.1.3 on 2018-11-23 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181123_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination', models.DecimalField(decimal_places=6, max_digits=9)),
                ('reason', models.TextField(blank=True, null=True)),
                ('site_fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sitefleet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
