# Generated by Django 2.1.5 on 2019-03-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190306_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetchecklistitem',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
    ]
