# Generated by Django 2.1.5 on 2019-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_fleetchecklistitem_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='current_trenching_distance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='isp_works_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ofc_works_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='original_trenching_distance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='osp_works_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_drawing',
            field=models.FileField(blank=True, null=True, upload_to='drawing/'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_powering_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='siterole',
            name='role',
            field=models.CharField(choices=[('isp', 'ISP'), ('osp', 'OSP'), ('osp_field_manager', 'OSP Field Manager'), ('osp_supervisor', 'OSP Supervisor'), ('quality', 'Quality'), ('ofc', 'OFC'), ('driver', 'Driver'), ('surveyor', 'Surveyor'), ('project_manager', 'Project Manager'), ('fleet_manager', 'Fleet Manager'), ('mechanic', 'Mechanic'), ('fuel_station_user', 'Fuel Station User'), ('warehouse', 'warehouse'), ('garage_manager', 'Garage Manager')], max_length=150),
        ),
    ]
