# Generated by Django 2.1.3 on 2018-11-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
