# Generated by Django 2.1.5 on 2019-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_site_site_usd_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='current_trenching_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='original_trenching_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
