# Generated by Django 2.1.3 on 2018-11-26 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20181126_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSiteFleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_driver_site_fleet', to='api.Sitefleet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_site_fleet', to='api.Site')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersitefleet',
            unique_together={('user', 'site_fleet')},
        ),
    ]
