# Generated by Django 2.1.3 on 2018-11-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181126_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersitefleet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_site_fleet', to='api.User'),
        ),
    ]
