# Generated by Django 2.1.5 on 2019-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190322_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfleetassignment',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
    ]
