# Generated by Django 2.1.3 on 2018-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], max_length=255, null=True),
        ),
    ]
