# Generated by Django 2.1.5 on 2019-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_userfleetassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfleetassignment',
            name='type',
            field=models.CharField(blank=True, choices=[('machine', 'Machine'), ('fleet', 'Fleet')], max_length=155, null=True),
        ),
    ]
