# Generated by Django 2.1.5 on 2019-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_userfleetassignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='handholeinstallation',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manholeassignment',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manholeinstallation',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reinstallation',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairhistory',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadcrossing',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trencheddistance',
            name='fm_approved',
            field=models.BooleanField(default=False),
        ),
    ]
