# Generated by Django 2.1.3 on 2018-11-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trencheddistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='running_out',
            field=models.BooleanField(default=False),
        ),
    ]
