# Generated by Django 2.1.5 on 2019-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190325_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfleetassignment',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
