# Generated by Django 2.1.5 on 2019-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userfleetassignment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancelled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='reason_for_cancellation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
