# Generated by Django 2.1.5 on 2019-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190327_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetfuelrequest',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
