# Generated by Django 2.1.3 on 2018-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_siteimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterole',
            name='userrole',
        ),
    ]
