# Generated by Django 2.1.5 on 2019-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190330_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
