# Generated by Django 2.1.3 on 2018-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_siterole_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterole',
            name='role',
            field=models.CharField(blank=True, choices=[('isp', 'ISP'), ('osp', 'OSP'), ('quality', 'Quality'), ('ofc', 'OFC'), ('driver', 'Driver'), ('surveyor', 'Surveyor'), ('project_manager', 'Project Manager'), ('fleet_manager', 'Fleet Manager')], max_length=150, null=True),
        ),
    ]
