# Generated by Django 2.1.3 on 2018-12-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_siterole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterole',
            name='role',
            field=models.CharField(choices=[('isp', 'ISP'), ('osp', 'OSP'), ('quality', 'Quality'), ('ofc', 'OFC'), ('driver', 'Driver'), ('surveyor', 'Surveyor'), ('project_manager', 'Project Manager'), ('fleet_manager', 'Fleet Manager')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterole',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siteroles_site', to='api.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterole',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siteroles_user', to='api.User'),
            preserve_default=False,
        ),
    ]
