# Generated by Django 2.1.5 on 2019-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190402_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='manholeduration',
            name='from_fibers',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='manholeduration',
            name='from_tube',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='manholeduration',
            name='to_fibers',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='manholeduration',
            name='to_tube',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
