# Generated by Django 2.1.3 on 2018-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20181217_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedocument',
            name='file',
            field=models.FileField(upload_to='sitedocuments'),
        ),
    ]
