# Generated by Django 2.1.5 on 2019-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_routechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairticket',
            name='object_id',
        ),
        migrations.AddField(
            model_name='repairticket',
            name='assessment_verification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='assessment_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='humanUuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='perform_fix',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='repairs_started',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='repairs_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairticket',
            name='requisition_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
