# Generated by Django 2.1.5 on 2019-04-04 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20190404_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_assgined_to', to='api.User'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('broken', 'Broken'), ('healty', 'Healty')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolassignment',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_assignment_tool', to='api.Tool'),
        ),
        migrations.AddField(
            model_name='toolassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_assignment_user', to='api.User'),
        ),
    ]
