# Generated by Django 2.1.3 on 2018-12-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_manholeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='can_client_view_survey_reports',
            field=models.BooleanField(default=False),
        ),
    ]
