# Generated by Django 2.1.5 on 2019-04-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_comment_appraisal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteworkstatus',
            name='site_role',
        ),
        migrations.AddField(
            model_name='siteworkstatus',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Site'),
        ),
        migrations.AddField(
            model_name='siteworkstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='siteworkstatus',
            name='work_status',
            field=models.CharField(choices=[('started', 'started'), ('stopped', 'stopped'), ('ongoing', 'ongoing'), ('resumed', 'resumed')], max_length=150),
        ),
    ]
