# Generated by Django 2.1.5 on 2019-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sitepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepower',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitepower',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
