# Generated by Django 2.1.5 on 2019-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sitepower'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepower',
            name='powering_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
