# Generated by Django 2.1.5 on 2019-04-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190411_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepower',
            name='end_time',
        ),
    ]
