# Generated by Django 2.1.5 on 2019-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('dual', 'Dual'), ('shared', 'Shared')], max_length=150, null=True),
        ),
    ]
