# Generated by Django 2.1.5 on 2019-05-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190507_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleetfuelrequest',
            old_name='fuel_amount',
            new_name='approved_amount',
        ),
        migrations.AddField(
            model_name='fleetfuelrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_request_approved_by', to='api.User'),
        ),
        migrations.AddField(
            model_name='fleetfuelrequest',
            name='fuelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_request_fuelled_by', to='api.User'),
        ),
        migrations.AddField(
            model_name='fleetfuelrequest',
            name='received_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
