# Generated by Django 2.1.5 on 2019-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20190507_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetfuelrequest',
            name='object_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
