# Generated by Django 2.1.5 on 2019-05-07 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_fleetfuelrequest_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuctInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('duct_type', models.CharField(blank=True, choices=[('HDPE', 'HDPE'), ('PVC', 'PVC')], max_length=155, null=True)),
                ('micro_duct', models.CharField(blank=True, choices=[('1_way', '1 Way'), ('2_way', '2 Way'), ('3_way', '3 Way')], max_length=155, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
