# Generated by Django 2.1.5 on 2019-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_cableinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='challenge'),
        ),
    ]
