# Generated by Django 2.1.5 on 2019-05-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_manhole_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='state',
            field=models.CharField(choices=[('picked_up', 'picked_up'), ('returned', 'returned'), ('removed', 'removed')], max_length=150, null=True),
        ),
    ]
