# Generated by Django 2.1.5 on 2019-05-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20190528_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfleetassignment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fleet_approver', to='api.User'),
        ),
    ]
