# Generated by Django 2.1.5 on 2019-05-29 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20190529_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCheckListItemResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('request_object_id', models.IntegerField(blank=True, null=True)),
                ('request_object_type', models.CharField(blank=True, choices=[('machine', 'Machine'), ('fleet', 'fleet')], max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'after')], max_length=50, null=True)),
                ('fleet_check_list_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Fleet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
