# Generated by Django 2.1.5 on 2019-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20190529_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetchecklistitem',
            name='type',
            field=models.CharField(blank=True, choices=[('fleet', 'Fleet'), ('machine', 'Machine')], max_length=255, null=True),
        ),
    ]
