# Generated by Django 2.1.5 on 2019-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20190531_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepower',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitepower',
            name='equipment_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitepower',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
