# Generated by Django 2.1.5 on 2019-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20190531_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('broken', 'Broken'), ('healty', 'Healty'), ('available', 'available'), ('broken_down', 'broken_down'), ('assigned', 'assigned')], max_length=50, null=True),
        ),
    ]
