# Generated by Django 2.1.5 on 2019-06-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20190605_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='activityimages'),
        ),
    ]
