# Generated by Django 2.1.5 on 2019-09-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20190730_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
