# Generated by Django 2.1.5 on 2019-09-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_repairticket_actual_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinstallation',
            name='material',
        ),
    ]
