# Generated by Django 2.1.5 on 2019-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20190924_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='odfinstallation',
            name='install_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odfinstallation',
            name='number_of_fiber_cables_terminated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odfinstallation',
            name='odf_labelled_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odfinstallation',
            name='odf_ports_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odfinstallation',
            name='odf_ports_terminated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odfinstallation',
            name='type_of_connectors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odfinstallation',
            name='type_of_odfs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
