# Generated by Django 2.1.5 on 2019-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_surveyresult_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_is_being_worked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
