# Generated by Django 2.1.5 on 2019-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_site_site_is_being_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='min_time',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='points',
        ),
        migrations.AddField(
            model_name='metric',
            name='type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('system', 'System')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='action',
            field=models.CharField(max_length=150),
        ),
    ]
