# Generated by Django 2.1.5 on 2019-11-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_metricresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformancemetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='userperformancemetric',
            name='points',
        ),
        migrations.AddField(
            model_name='userperformancemetric',
            name='metric_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MetricResult'),
        ),
    ]
