---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- apt: name={{ item }} state=present
  with_items:
  - python3-pip
  - git
  - python3-dev

- pip: name={{ item }}
  with_items:
  - pipenv
  - virtualenv

- name: create inow directory
  file: path=/home/{{name}}/app/{{ name }} mode=0755 state=directory

- name: send key to remote deploy user
  copy: src=keys/webapp dest=/home/{{name}}/.ssh/webapp mode=0600


- name: checkout from bitbucket
  git: repo={{repo}} dest=/home/{{name}}/app/{{ name }} key_file=/home/{{ user }}/.ssh/webapp accept_hostkey=true force=yes


- command: 'pipenv install'
  args:
    chdir: /home/{{name}}/app/{{name}}/
  environment:
    PIPENV_VENV_IN_PROJECT: 1


- template: src=local_settings.py.j2 dest=/home/{{name}}/app/{{name}}/{{name}}/local_settings.py


- command: /home/{{name}}/app/{{ name }}/.venv/bin/python manage.py migrate --noinput
  args:
    chdir: /home/{{name}}/app/{{ name }}

- command: /home/{{name}}/app/{{ name }}/.venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /home/{{name}}/app/{{ name }}

- name: start tukole service
  systemd:
    state: restarted
    name: tukole

- service: name=uwsgi state=restarted
  become: yes

- service: name=nginx state=restarted
  become: yes
