---

- name: adding service to tukole
  template: src=tukole.service.j2 dest=/etc/systemd/system/tukole.service
  become_user: root

- name: start tukole service
  systemd:
    state: restarted
    name: tukole